name: music
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  shared_preferences: ^2.0.18
  share_plus: ^8.0.2
  sliver_tools: ^0.2.12
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: BoxIcons
      fonts:
        - asset: assets/fonts/boxicons.ttf
  uses-material-design: true
  generate: true
